version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bbb
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=database
  web:
    build: ./
    command: gunicorn travel.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume: