# Generated by Django 4.0 on 2021-12-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
