# Generated by Django 4.0 on 2022-03-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0003_alter_userevent_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерей'},
        ),
        migrations.AlterModelOptions(
            name='travelcity',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Городы'},
        ),
        migrations.AlterModelOptions(
            name='travelevent',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='userevent',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='country',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Country/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='Kazakhstan', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='Gallery/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Названия'),
        ),
        migrations.AlterField(
            model_name='travelcity',
            name='city_name',
            field=models.CharField(max_length=255, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='travelcity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='travelcity',
            name='image',
            field=models.ImageField(upload_to='City/', verbose_name='Фотография города'),
        ),
        migrations.AlterField(
            model_name='travelcity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='travelcity',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='travelevent',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончание'),
        ),
        migrations.AlterField(
            model_name='travelevent',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начало'),
        ),
        migrations.AlterField(
            model_name='travelevent',
            name='travelCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.travelcity', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.travelevent', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auth.user', verbose_name='Пользователь'),
        ),
    ]
