# Generated by Django 4.0 on 2022-03-31 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_country_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='FlightCompany/')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компаний',
            },
        ),
        migrations.AddField(
            model_name='travelcity',
            name='description',
            field=models.TextField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HotelToCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('star', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='Hotel/')),
                ('link_to', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='main.travelcity')),
            ],
            options={
                'verbose_name': 'Отел',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='FlightToCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_time', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('link_to', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='main.travelcity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.flightcompany')),
            ],
            options={
                'verbose_name': 'Авияперелет',
                'verbose_name_plural': 'Авияперелеты',
            },
        ),
    ]
