# Generated by Django 4.0 on 2022-03-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_flightcompany_travelcity_description_hoteltocity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttocity',
            name='from_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
