# Generated by Django 4.0 on 2022-05-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_flighttocity_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightcompany',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='flighttocity',
            options={'verbose_name': 'Авиаперелет', 'verbose_name_plural': 'Авиаперелеты'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='travelcity',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
