# Generated by Django 4.0 on 2022-06-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_flightcompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hoteltocity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='travelcity',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
